// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portlite.Infrastructure.Persistence;

#nullable disable

namespace Portlite.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PortliteDbContext))]
    [Migration("20260507091701_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Portlite.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Assets", (string)null);
                });

            modelBuilder.Entity("Portlite.Domain.Entities.CashTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SubPortfolioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.ComplexProperty<Dictionary<string, object>>("Amount", "Portlite.Domain.Entities.CashTransaction.Amount#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 6)
                                .HasColumnType("decimal(18,6)")
                                .HasColumnName("Amount");

                            b1.Property<int>("Currency")
                                .HasColumnType("int")
                                .HasColumnName("Currency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("SubPortfolioId", "OccurredAt");

                    b.ToTable("CashTransactions", (string)null);
                });

            modelBuilder.Entity("Portlite.Domain.Entities.PortfolioValueSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("SubPortfolioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.ComplexProperty<Dictionary<string, object>>("CostBasis", "Portlite.Domain.Entities.PortfolioValueSnapshot.CostBasis#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 6)
                                .HasColumnType("decimal(18,6)")
                                .HasColumnName("CostBasis_Amount");

                            b1.Property<int>("Currency")
                                .HasColumnType("int")
                                .HasColumnName("CostBasis_Currency");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("MarketValue", "Portlite.Domain.Entities.PortfolioValueSnapshot.MarketValue#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 6)
                                .HasColumnType("decimal(18,6)")
                                .HasColumnName("MarketValue_Amount");

                            b1.Property<int>("Currency")
                                .HasColumnType("int")
                                .HasColumnName("MarketValue_Currency");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("RealizedPnL", "Portlite.Domain.Entities.PortfolioValueSnapshot.RealizedPnL#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 6)
                                .HasColumnType("decimal(18,6)")
                                .HasColumnName("RealizedPnL_Amount");

                            b1.Property<int>("Currency")
                                .HasColumnType("int")
                                .HasColumnName("RealizedPnL_Currency");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("UnrealizedPnL", "Portlite.Domain.Entities.PortfolioValueSnapshot.UnrealizedPnL#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 6)
                                .HasColumnType("decimal(18,6)")
                                .HasColumnName("UnrealizedPnL_Amount");

                            b1.Property<int>("Currency")
                                .HasColumnType("int")
                                .HasColumnName("UnrealizedPnL_Currency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("SubPortfolioId", "Date")
                        .IsUnique();

                    b.ToTable("PortfolioValueSnapshots", (string)null);
                });

            modelBuilder.Entity("Portlite.Domain.Entities.PriceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssetSymbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal?>("High")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("Low")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("Open")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssetSymbol", "Date")
                        .IsUnique();

                    b.ToTable("PriceSnapshots", (string)null);
                });

            modelBuilder.Entity("Portlite.Domain.Entities.SubPortfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SubPortfolios", (string)null);
                });

            modelBuilder.Entity("Portlite.Domain.Entities.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssetSymbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Fee")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("Side")
                        .HasColumnType("int");

                    b.Property<Guid>("SubPortfolioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssetSymbol");

                    b.HasIndex("SubPortfolioId", "ExecutedAt");

                    b.ToTable("Trades", (string)null);
                });

            modelBuilder.Entity("Portlite.Domain.Entities.Asset", b =>
                {
                    b.OwnsOne("Portlite.Domain.Entities.OptionDetail", "OptionDetail", b1 =>
                        {
                            b1.Property<Guid>("AssetId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("Expiry")
                                .HasColumnType("date")
                                .HasColumnName("Option_Expiry");

                            b1.Property<int>("Multiplier")
                                .HasColumnType("int")
                                .HasColumnName("Option_Multiplier");

                            b1.Property<int>("OptionType")
                                .HasColumnType("int")
                                .HasColumnName("Option_Type");

                            b1.Property<decimal>("Strike")
                                .HasPrecision(18, 6)
                                .HasColumnType("decimal(18,6)")
                                .HasColumnName("Option_Strike");

                            b1.Property<string>("UnderlyingSymbol")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Option_UnderlyingSymbol");

                            b1.HasKey("AssetId");

                            b1.ToTable("Assets");

                            b1.WithOwner()
                                .HasForeignKey("AssetId");
                        });

                    b.Navigation("OptionDetail");
                });

            modelBuilder.Entity("Portlite.Domain.Entities.CashTransaction", b =>
                {
                    b.HasOne("Portlite.Domain.Entities.SubPortfolio", "SubPortfolio")
                        .WithMany("CashTransactions")
                        .HasForeignKey("SubPortfolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubPortfolio");
                });

            modelBuilder.Entity("Portlite.Domain.Entities.PortfolioValueSnapshot", b =>
                {
                    b.HasOne("Portlite.Domain.Entities.SubPortfolio", "SubPortfolio")
                        .WithMany("ValueSnapshots")
                        .HasForeignKey("SubPortfolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubPortfolio");
                });

            modelBuilder.Entity("Portlite.Domain.Entities.PriceSnapshot", b =>
                {
                    b.HasOne("Portlite.Domain.Entities.Asset", "Asset")
                        .WithMany("PriceSnapshots")
                        .HasForeignKey("AssetSymbol")
                        .HasPrincipalKey("Symbol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Portlite.Domain.Entities.Trade", b =>
                {
                    b.HasOne("Portlite.Domain.Entities.Asset", "Asset")
                        .WithMany("Trades")
                        .HasForeignKey("AssetSymbol")
                        .HasPrincipalKey("Symbol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Portlite.Domain.Entities.SubPortfolio", "SubPortfolio")
                        .WithMany("Trades")
                        .HasForeignKey("SubPortfolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("SubPortfolio");
                });

            modelBuilder.Entity("Portlite.Domain.Entities.Asset", b =>
                {
                    b.Navigation("PriceSnapshots");

                    b.Navigation("Trades");
                });

            modelBuilder.Entity("Portlite.Domain.Entities.SubPortfolio", b =>
                {
                    b.Navigation("CashTransactions");

                    b.Navigation("Trades");

                    b.Navigation("ValueSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
