<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>c10eb4eb-57ef-425f-a08b-f66572dd7d47</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Portlite.Domain\Portlite.Domain.csproj" />
    <ProjectReference Include="..\Portlite.Shared\Portlite.Shared.csproj" />
    <ProjectReference Include="..\Portlite.Infrastructure\Portlite.Infrastructure.csproj" />
  </ItemGroup>

</Project>
